version: '3.8'
services:
  billing:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: speechify_billing
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
