import { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('subscription_plans').del();

  // Insert subscription plans
  const plans = [
    // Free Plans
    {
      id: uuidv4(),
      stripe_product_id: 'prod_free_monthly',
      stripe_price_id: 'price_free_monthly',
      name: 'Free Plan',
      description: 'Perfect for trying out Speechify with basic features',
      plan_type: 'free',
      amount: 0.0,
      currency: 'usd',
      billing_interval: 'month',
      billing_interval_count: 1,
      usage_limit: 10000,
      features: JSON.stringify({
        api_calls: 10000,
        characters_per_month: 50000,
        voice_minutes: 60,
        voices: ['basic'],
        support: 'community',
        analytics: false,
        custom_voices: false,
        team_collaboration: false,
      }),
      is_active: true,
    },
    // Premium Monthly
    {
      id: uuidv4(),
      stripe_product_id: 'prod_premium_monthly',
      stripe_price_id: 'price_premium_monthly',
      name: 'Premium Plan',
      description: 'Great for individuals and small teams',
      plan_type: 'premium',
      amount: 9.99,
      currency: 'usd',
      billing_interval: 'month',
      billing_interval_count: 1,
      usage_limit: 100000,
      features: JSON.stringify({
        api_calls: 100000,
        characters_per_month: 500000,
        voice_minutes: 600,
        voices: ['basic', 'premium'],
        support: 'email',
        analytics: true,
        custom_voices: false,
        team_collaboration: false,
        priority_processing: true,
      }),
      is_active: true,
    },
    // Premium Yearly (with discount)
    {
      id: uuidv4(),
      stripe_product_id: 'prod_premium_yearly',
      stripe_price_id: 'price_premium_yearly',
      name: 'Premium Plan (Yearly)',
      description: 'Save 20% with annual billing',
      plan_type: 'premium',
      amount: 95.9, // ~$8/month = 20% discount
      currency: 'usd',
      billing_interval: 'year',
      billing_interval_count: 1,
      usage_limit: 100000,
      features: JSON.stringify({
        api_calls: 100000,
        characters_per_month: 500000,
        voice_minutes: 600,
        voices: ['basic', 'premium'],
        support: 'email',
        analytics: true,
        custom_voices: false,
        team_collaboration: false,
        priority_processing: true,
        annual_discount: true,
      }),
      is_active: true,
    },
    // Pro Monthly
    {
      id: uuidv4(),
      stripe_product_id: 'prod_pro_monthly',
      stripe_price_id: 'price_pro_monthly',
      name: 'Pro Plan',
      description: 'For professionals and growing businesses',
      plan_type: 'pro',
      amount: 19.99,
      currency: 'usd',
      billing_interval: 'month',
      billing_interval_count: 1,
      usage_limit: 1000000,
      features: JSON.stringify({
        api_calls: 1000000,
        characters_per_month: 5000000,
        voice_minutes: 6000,
        voices: ['basic', 'premium', 'neural'],
        support: 'priority',
        analytics: true,
        custom_voices: true,
        team_collaboration: true,
        priority_processing: true,
        custom_integrations: true,
        white_label: false,
      }),
      is_active: true,
    },
    // Pro Yearly (with discount)
    {
      id: uuidv4(),
      stripe_product_id: 'prod_pro_yearly',
      stripe_price_id: 'price_pro_yearly',
      name: 'Pro Plan (Yearly)',
      description: 'Save 20% with annual billing',
      plan_type: 'pro',
      amount: 191.9, // ~$16/month = 20% discount
      currency: 'usd',
      billing_interval: 'year',
      billing_interval_count: 1,
      usage_limit: 1000000,
      features: JSON.stringify({
        api_calls: 1000000,
        characters_per_month: 5000000,
        voice_minutes: 6000,
        voices: ['basic', 'premium', 'neural'],
        support: 'priority',
        analytics: true,
        custom_voices: true,
        team_collaboration: true,
        priority_processing: true,
        custom_integrations: true,
        white_label: false,
        annual_discount: true,
      }),
      is_active: true,
    },
    // EUR Plans
    {
      id: uuidv4(),
      stripe_product_id: 'prod_premium_monthly_eur',
      stripe_price_id: 'price_premium_monthly_eur',
      name: 'Premium Plan (EUR)',
      description: 'Great for individuals and small teams',
      plan_type: 'premium',
      amount: 9.99,
      currency: 'eur',
      billing_interval: 'month',
      billing_interval_count: 1,
      usage_limit: 100000,
      features: JSON.stringify({
        api_calls: 100000,
        characters_per_month: 500000,
        voice_minutes: 600,
        voices: ['basic', 'premium'],
        support: 'email',
        analytics: true,
      }),
      is_active: true,
    },
    {
      id: uuidv4(),
      stripe_product_id: 'prod_pro_monthly_eur',
      stripe_price_id: 'price_pro_monthly_eur',
      name: 'Pro Plan (EUR)',
      description: 'For professionals and growing businesses',
      plan_type: 'pro',
      amount: 19.99,
      currency: 'eur',
      billing_interval: 'month',
      billing_interval_count: 1,
      usage_limit: 1000000,
      features: JSON.stringify({
        api_calls: 1000000,
        characters_per_month: 5000000,
        voice_minutes: 6000,
        voices: ['basic', 'premium', 'neural'],
        support: 'priority',
        analytics: true,
        custom_voices: true,
        team_collaboration: true,
      }),
      is_active: true,
    },
    // GBP Plans
    {
      id: uuidv4(),
      stripe_product_id: 'prod_premium_monthly_gbp',
      stripe_price_id: 'price_premium_monthly_gbp',
      name: 'Premium Plan (GBP)',
      description: 'Great for individuals and small teams',
      plan_type: 'premium',
      amount: 8.99,
      currency: 'gbp',
      billing_interval: 'month',
      billing_interval_count: 1,
      usage_limit: 100000,
      features: JSON.stringify({
        api_calls: 100000,
        characters_per_month: 500000,
        voice_minutes: 600,
        voices: ['basic', 'premium'],
        support: 'email',
        analytics: true,
      }),
      is_active: true,
    },
    {
      id: uuidv4(),
      stripe_product_id: 'prod_pro_monthly_gbp',
      stripe_price_id: 'price_pro_monthly_gbp',
      name: 'Pro Plan (GBP)',
      description: 'For professionals and growing businesses',
      plan_type: 'pro',
      amount: 17.99,
      currency: 'gbp',
      billing_interval: 'month',
      billing_interval_count: 1,
      usage_limit: 1000000,
      features: JSON.stringify({
        api_calls: 1000000,
        characters_per_month: 5000000,
        voice_minutes: 6000,
        voices: ['basic', 'premium', 'neural'],
        support: 'priority',
        analytics: true,
        custom_voices: true,
        team_collaboration: true,
      }),
      is_active: true,
    },
  ];

  await knex('subscription_plans').insert(plans);

  const { logger } = require('../../src/utils/logger');
  logger.info('✅ Subscription plans seeded successfully');
  logger.info(`   📋 Created ${plans.length} subscription plans`);
  logger.info('   💰 Currencies: USD, EUR, GBP');
  logger.info('   📅 Intervals: Monthly, Yearly');
  logger.info('   🎯 Tiers: Free, Premium, Pro');
}
